-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_allowed_topic
(
    id bigserial NOT NULL,
	topic_vec vector,
	topic text COLLATE pg_catalog."default",
    CONSTRAINT app_allowed_topic_pkey PRIMARY KEY (id)
);
END;




BEGIN;
CREATE TABLE IF NOT EXISTS public.app_allowed_topic_v2
(
    id bigserial NOT NULL,
	content_vec vector,
	topic text COLLATE pg_catalog."default",
	content text COLLATE pg_catalog."default",
    CONSTRAINT app_allowed_topic_v2_pkey PRIMARY KEY (id)
);
END;


SELECT topic FROM app_allowed_topic_v2 WHERE topic like 'answer%';



CREATE TABLE IF NOT EXISTS public.app_benchmark_topic
(
    id bigserial NOT NULL,
	text_vec vector,
	text text COLLATE pg_catalog."default",
	topic text COLLATE pg_catalog."default",
    CONSTRAINT app_benchmark_topic_pkey PRIMARY KEY (id)
);
END;



DROP TABLE  app_benchmark_topic;




-- DROP TABLE chat_history;
-- Create the chat_history table
DROP TABLE chat_history;
DROP TABLE va_stage;

CREATE TABLE IF NOT EXISTS chat_history (
    id SERIAL PRIMARY KEY,
    msisdn VARCHAR(20) NOT NULL,
    campaign VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    source VARCHAR(100) NOT NULL,
    whatsapp_id VARCHAR(100) NOT NULL,
    sending_date TIMESTAMP NOT NULL,
	readed BOOL DEFAULT FALSE,
	collected BOOL DEFAULT FALSE
);

-- Add indexes
CREATE INDEX idx_msisdn ON chat_history (msisdn);
CREATE INDEX idx_campaign ON chat_history (campaign);
CREATE INDEX idx_whatsapp_id ON chat_history (whatsapp_id);


CREATE TABLE IF NOT EXISTS va_stage (
    id SERIAL PRIMARY KEY,
    msisdn VARCHAR(20) NOT NULL,
    campaign VARCHAR(20) NOT NULL,
    state VARCHAR(20) NOT NULL,
    last_update TIMESTAMP NOT NULL
);

-- Add indexes
CREATE INDEX idva_msisdn ON va_stage (msisdn);
CREATE INDEX idva_campaign ON va_stage (campaign);



SELECT * FROM chat_history ORDER by id DESC;
SELECT * FROM va_stage ORDER by id DESC;





